[ADD] Express 초기 환경세팅 과제 제출
wecode-bootcamp-korea/42-backend-westagram-1 pull request #2
Opened 2023-01-19 05:24 UTC by ksh0123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [V] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - Express 초기 환경세팅 과제 제출

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express 초기 환경 설정
- TypeORM / dbConnection 설정

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-01-19 08:14 UTC, sangwoong03 requested changes

2023-01-19 08:14 UTC, sangwoong03 commented on shinhye/app.js
> +});
typeorm의 공식문서를 확인해주세요! (구두 전달 완료)

```suggestion
myDataSource.initialize()
  .then(() => {
    console.log("Data Source has been initialized!");
  })
  .catch((err) => {
    console.error(' 에러메시지 ');
  });
```

2023-01-19 08:14 UTC, sangwoong03 commented on shinhye/app.js
> +const myDataSource = new DataSource({
myDataSource와 같이 my라는 표현은 지양하는 것이 좋습니다.
서버를 가리키는지? 코드를 작성한 개발자를 가리키는지? 아니면 ... 이 어플리케이션 자체를 가리키는지?

그렇기 때문에 다음과 같이 수정할 수 있습니다.
```suggestion
const dataSource = new DataSource({
// const appDataSource = new DataSource({
// const mysqlDataSource = new DataSource({
```

2023-01-19 08:14 UTC, sangwoong03 commented on shinhye/app.js
> +const { DataSource } = require("typeorm");
구두 전달 완료

```suggestion
require("dotenv").config();

const express = require("express");
const cors = require("cors");
const morgan = require('morgan');
const { DataSource } = require("typeorm");

const app = express()
app.use(cors());
app.use(morgan('combined'));


```

2023-01-19 08:14 UTC, sangwoong03 commented on shinhye/app.js
> +});
1. function 키워드 함수 vs 화살표 함수 차이
2. 함수가 종료되는 구문에서는 return 키워드 사용

```suggestion
app.get("/ping", (req, res) => {
  return res.json({message: "pong"});
});
```

2023-01-19 08:14 UTC, sangwoong03 commented on shinhye/app.js
> +});
과제1) 화살표 함수를 사용하도록 수정해주세요!
과제2) .env 파일에서 PORT라는 변수에 8000이라는 값을 할당하여 해당 PORT를 사용하여 서버를 실행해주세요!

2023-01-21 07:15 UTC, ksh0123 commented on shinhye/app.js
> +});
확인 후 반영했습니다 감사합니다!

2023-01-21 07:15 UTC, ksh0123 commented on shinhye/app.js
> +});
확인 후 반영했습니다 감사합니다!

2023-01-21 07:15 UTC, ksh0123 commented on shinhye/app.js
> +const { DataSource } = require("typeorm");
확인 후 반영했습니다 감사합니다!

2023-01-21 07:15 UTC, ksh0123 commented on shinhye/app.js
> +const myDataSource = new DataSource({
확인 후 반영했습니다 감사합니다!

2023-01-21 07:15 UTC, ksh0123 commented on shinhye/app.js
> +});
확인 후 반영했습니다 감사합니다!

2023-01-22 03:51 UTC, sangwoong03 approved these changes
고생하셨습니다!! 깔끔하게 잘 작성해주셨어요.
LGTM 👍

다음 PR 작성 할 땐 두가지 사항을 확인해주세요!

- 제목은 다음과 같이 작성해주세요.
`[OO기 - 김코드] 과제O: 회원가입 기능 구현`

- 브랜치 명은 다음과 같이 설정해주세요.
`feature/kimcode-signup`

2023-01-22 03:51 UTC, merged