[ADD] 유저 회원가입
wecode-bootcamp-korea/42-backend-westagram-1 pull request #4
Opened 2023-01-19 06:56 UTC by jangjuseong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유저 회원가입 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 유저 회원가입 기능 추가

<br />

## :: 테스트 결과 이미지
<img width="1512" alt="스크린샷 2023-01-19 오후 3 51 47" src="https://user-images.githubusercontent.com/115794886/213375662-3254454e-3617-43ea-87b2-8b3775059ea0.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-20 01:39 UTC, sangwoong03 requested changes

2023-01-20 01:39 UTC, sangwoong03 commented on jangjuseong/app.js
> +});
엔드포인트 url을 포함하여 내부 로직 코드를 깔끔하게 잘 작성해주셨네요!

1. 두번째 인수로 받는 콜백 함수의 parameter 중 next 함수는 콜백 함수 내부 로직에서 사용하고 있지 않으니 삭제해주세요!
2. 39번 라인에서 `profile_image` 변수를 구조분해 할당으로 값을 가져오고 있습니다. 다만 JavaScript 언어 고유의 컨벤션 중 하나로 단어 간 띄어쓰기를 해야하는 경우 camelCase를 적용하는 것이 일반적입니다. 언어에 대한 컨벤션도 잘 지키면 가독성과 유지 보수 측면에서도 유리해질 것 같네요!
3. 지금도 충분히 가독성이 좋지만 raw query를 작성하는 부분에서 포맷팅을 조금만 수정해주면 너무 좋을 것  같네요!
4. 함수가 종료되는 부분에는 return 키워드를 포함하여 내가 의도한 코드 이외의 코드가 추가로 실행되지 않도록 작성해주세요!

```suggestion
app.post('/users/signup', async (req, res) => {
  const { name, email, password, profileImage } = req.body;

  await mysqlDataSource.query(
    `INSERT INTO users (
        name,
        email,
        password,
        profile_image
      )
      VALUES (
        ?,
        ?,
        ?,
        ?
      );
    `,
    [name, email, password, profile_image]
  );

  res.status(200).json({ message: 'userCreated' });
});
```

2023-01-20 01:39 UTC, sangwoong03 commented on jangjuseong/db/migrations/20230119053017_users.sql
> +);
users 테이블에 대한 schema도 잘 설계해주셨네요!

우리가 일반적으로 사용하는 많은 웹사이트를 생각해보면, email이나 유저의 id (계정)에 대해 중복 체크를 확인하는 부분이 있습니다.
클라이언트 (Front-end)단에서 정규표현식을 통해 충분히 처리를 할 수 있지만, 클라이언트를 거치지 않고 외부에서 강압적으로 데이터를 주입하는 경우도 분명 존재할텐데요.

그럴 경우를 방지하여 유저에게 id 이외의 고유한 정보를 받는 경우 해당 컬럼에 대해 unique키 속성을 추가하여 중복되는 데이터가 추가되는 것을 방지할 수 있습니다.

아래와 같이 제약 조건의 이름을 설정할 수도 있습니다.
```suggestion
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    profile_image VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT users_email_ukey UNIQUE(email)
);
```

2023-01-20 01:39 UTC, sangwoong03 commented on jangjuseong/db/schema.sql
> +
해당 파일은 `.gitignore` 파일에 추가해주세요!
현재 `.gitignore` 파일이 주성님 디렉토리 상에 보이지 않지만, 최상단에 위치해있는 `.gitignore` 파일의 영향을 받고 있어 `.env` 파일이나 `node_modules` 폴더가 보이지 않는 것 같습니다.

주성님 작업 폴더 내부에서도 `.gitignore` 파일을 생성한 다음 `db/schema.sql` 을 추가하여 해당 파일이 GitHub 상에서 공유되지 않도록 수정해주세요!

이미 GitHub 상에 push 된 내역을 지우는 커맨드는 아래와 같습니다.
`git rm --cached "filepath"`

적용이 잘 안된다면 커멘트 달아주세요!

2023-01-20 02:04 UTC, jangjuseong commented on jangjuseong/app.js
> +});
상웅님 리뷰 감사합니다~ 
4번 항목의 '함수가 종료되는 부분에는 return 키워드를 포함하여 내가 의도한 코드 이외의 코드가 추가로 실행되지 않도록 작성해주세요!' 에 대한 이해가 잘 가지 않습니다. 추가적으로 설명 부탁드립니다!

2023-01-20 02:21 UTC, jangjuseong commented on jangjuseong/db/schema.sql
> +
![스크린샷 2023-01-20 오전 11 20 01(2)](https://user-images.githubusercontent.com/115794886/213604286-c5b3ef63-0a49-4fd3-83d0-d6e46ad038a6.png)
git rm --cached "filepath"가 잘 적용되지 않습니다

2023-01-20 02:48 UTC, jangjuseong commented on jangjuseong/db/schema.sql
> +
![스크린샷 2023-01-20 오전 11 44 40(2)](https://user-images.githubusercontent.com/115794886/213607233-8c46b37e-5ad9-4641-a16c-59641bc41071.png)
filepath 부분에 경로를 입력했어야 하는데 , 그대로 "filepath"라고 적어서 그랬던것이었습니다! ㅎㅎ

2023-01-20 02:50 UTC, jangjuseong commented on jangjuseong/db/schema.sql
> +
그런데 github repository 상에서는 지워지지가 않는 것 같습니다

2023-01-22 04:02 UTC, sangwoong03 requested changes

2023-01-22 04:02 UTC, sangwoong03 commented on jangjuseong/db/migrations/20230120021617_users.sql
> +);
이 부분 indentation (들여쓰기) 적용해서 가독성을 높여주면 좋을 것 같습니다!

추가로, 나중에 비밀번호를 암호화하여 저장을 할 텐데, 암호화 된 비밀번호는 varchar() 보다는 binary() 값으로도 저장할 수도 있습니다.
mysql 공식문서에서 더 많은 타입을 찾아보고 적용해보면 좋을 것 같습니다!!


```suggestion
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    profile_image VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT users_email_ukey UNIQUE(email)
);
```

2023-01-22 08:13 UTC, sangwoong03 approved these changes, later dismissed
고생하셨습니다 LGTM 👍

2023-01-22 09:16 UTC, sangwoong03 approved these changes
고생하셨습니다 주성님
컨플릭트도 잘 해결해주셨네요! 👍

2023-01-22 09:16 UTC, merged