feature/CRUD
wecode-bootcamp-korea/42-backend-westagram-1 pull request #6
Opened 2023-01-23 07:13 UTC by jangjuseong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- westagram CRUD 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 게시글 등록하기, 전체 게시글 조회하기, 유저의 게시글 조회하기, 게시글 수정하기, 게시글 삭제하기, 좋아요 누르기 기능 추가

<br />

## :: 테스트 결과 이미지
<img width="840" alt="게시글 등록" src="https://user-images.githubusercontent.com/115794886/213983833-92d27fc7-1b9c-46ed-8cd1-29eaaccd5de6.png">
<img width="843" alt="게시글 삭제" src="https://user-images.githubusercontent.com/115794886/213983838-ced5e29f-cf9a-4d00-a18f-65884345f1c9.png">
<img width="840" alt="게시글 수정하기" src="https://user-images.githubusercontent.com/115794886/213983840-9281dcc4-485f-4a8a-9e95-07b2258cffa6.png">
<img width="878" alt="전체 게시글 조회" src="https://user-images.githubusercontent.com/115794886/213983842-0a7436d7-9ac8-40f8-8c64-16731325c074.png">
<img width="839" alt="특정 유저 게시글 조회" src="https://user-images.githubusercontent.com/115794886/213983845-47c863e9-0579-4705-bd1e-56e6e781a7a3.png">
<img width="848" alt="좋아요 누르기" src="https://user-images.githubusercontent.com/115794886/213983843-72b3ccc8-fc1d-427b-be6e-f2d9e82faa16.png">
<img width="851" alt="터미널" src="https://user-images.githubusercontent.com/115794886/213983873-db82b73d-d8a3-4834-8d28-a82dd24d3124.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-25 05:22 UTC, kyeongraekim requested changes, later dismissed

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/app.js
> +app.post('/posts/users', async (req, res) => {
- 게시글에 대한 등록 API임으로 엔드포인트 설계가 /posts 정도로 되어도 무방할 것으로 보이네요! 두개의 다른 리소스가 엔드포인트에 명시 되어있어서 혼선을 야기할 수 있는데 이는, RESTful 한 엔드포인트 설계처럼 보여지지 않습니다.

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/app.js
> +});
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM posts`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const posts = await myDataSource.query(`SELECT * FROM posts`);
      
      res.status(200).json({ data : posts})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/app.js
> +app.get('/posts/lookup', async (req, res) => {
- 이곳의 엔드포인트를 보다 RESTful 하게 설정할 수 있도록 뒤에 /lookup 이라는 불필요한 동사적 어구는 삭제해주세요!
- get이라는 http 메소드에서 해당 엔드포인트가 행하고자 하는 동사적 기능이 충분히 설명되어 있기에 lookup이라는 동사 정의는 엔드포인트에 또 내려주실 필요가 없습니다.

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/app.js
> +app.get('/posts/lookup/:userId', async (req, res) => {
- posts/user/1 정도로 정의 내려서 뒤에 붙는 정수값의 아이디 형태의 숫자 정보가 posts와 연관되어잇는지 user와 연관되어있는지 보기좋게 명시해주세요!

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/db/migrations/20230123045628_likes.sql
> +);
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2023-01-25 05:22 UTC, kyeongraekim commented on jangjuseong/app.js
> +});
- 해당 내용은 전체 코드를 살펴보신 후 필요한 부분에 모두 수정 적용을 해주세요!
-

2023-01-25 17:18 UTC, jangjuseong commented
<img width="1507" alt="스크린샷 2023-01-26 오전 2 13 14" src="https://user-images.githubusercontent.com/115794886/214634541-7aba5c46-1ea4-4046-bd10-5652fbe7bee3.png">
갑자기 push가 안됩니다. 해결 방안 구글링 해봐도 못찾겠어서 도움요청 라벨 남깁니다!

2023-01-26 02:36 UTC, jangjuseong commented
> 



> <img alt="스크린샷 2023-01-26 오전 2 13 14" width="1507" src="https://user-images.githubusercontent.com/115794886/214634541-7aba5c46-1ea4-4046-bd10-5652fbe7bee3.png">
> 
> 갑자기 push가 안됩니다. 해결 방안 구글링 해봐도 못찾겠어서 도움요청 라벨 남깁니다!



> <img alt="스크린샷 2023-01-26 오전 2 13 14" width="1507" src="https://user-images.githubusercontent.com/115794886/214634541-7aba5c46-1ea4-4046-bd10-5652fbe7bee3.png">
> 
> 갑자기 push가 안됩니다. 해결 방안 구글링 해봐도 못찾겠어서 도움요청 라벨 남깁니다!

해결했습니다!

2023-01-26 05:12 UTC, sangwoong03 requested changes
주성님 고생하셨습니다~!

추가 피드백 확인 후 수정해주세요!

2023-01-26 05:12 UTC, sangwoong03 commented on jangjuseong/app.js
> +app.get('/posts/user/:userId', async (req, res) => {
이미 `:userId`라는 path parameter를 사용하기 때문에 posts 뒤의 /user path는 명시하지 않아도 될 것 같습니다.
```suggestion
app.get('/posts/:userId', async (req, res) => {
```

2023-01-26 05:12 UTC, sangwoong03 commented on jangjuseong/app.js
> +    .then((data) => res.status(200).json({ data }));
- async/await 키워드를 사용하고 있기 때문에 then() 함수를 통해 비동기 함수를 처리할 필요가 없습니다.
- SQL 쿼리 포매팅을 다음과 같이 수정해주면 구조 파악이 용이해지고 가독성도 좋아질 것 같습니다.

```suggestion
  const [result] = await mysqlDataSource.query(`
    SELECT
      u.id AS userId,
      u.profile_image AS userProfileImage,
      pi.post_informations AS postings
    FROM users u
    INNER JOIN (
      SELECT
        user_id,
        JSON_ARRAYAGG(
          JSON_OBJECT (
            "postingId", id,
            "postingImageUrl", post_image_url,
            "postingContent", content
          )
        ) AS postInformations
      FROM posts
      GROUP BY user_id
    ) pi 
      ON pi.user_id = u.id
    WHERE u.id = ?;
    `, [ userId ])
    return res.status(200).json({ data: result }));
```

2023-01-26 05:12 UTC, sangwoong03 commented on jangjuseong/app.js
> +app.patch('/posts/:postId/user/:userId', async (req, res) => {
해당 부분 엔드포인트도 user라는 부분을 명시하지 않아도 될 것 같습니다.

```suggestion
app.patch('/posts/:postId/:userId', async (req, res) => {
```

2023-01-26 05:12 UTC, sangwoong03 commented on jangjuseong/app.js
> +  );
`userId`와 `postId`도 `?` 매핑할 수 있도록 수정해주세요!
```suggestion
  await mysqlDataSource.query(
    `UPDATE posts
    SET
      content = ?
    WHERE 
      user_id = ? AND id = ?
    `, [ content, userId, postId ]
  );
```

2023-01-26 05:12 UTC, sangwoong03 commented on jangjuseong/app.js
> +    .then((data) => res.status(201).json({ data }));
- 해당 부분도 await 키워드를 사용하면서 then() 함수로 비동기 함수를 처리하고 있네요!
- 포매팅까지 수정해주면 너무 좋을 것 같습니다.
- `?` 를 활용하여 데이터 매핑을 할 수 있도록 수정해주세요!

```suggestion
  const [result] = await mysqlDataSource.query(`
    SELECT
      u.id AS userId,
      u.profile_image AS userProfileImage,
      p.id AS postingId,
      p.post_image_url AS postingImageUrl,
      p.content AS postingContent
    FROM posts p
    INNER JOIN users u ON u.id = p.user_id
    WHERE u.id = ? AND p.id = ?
    `, [ userId, postId ])
   
   return res.status(201).json({ data: result }));
```

2023-01-26 08:21 UTC, sangwoong03 commented on jangjuseong/app.js
> +    WHERE posts.id = ${postId}
`?` 매핑을 통해 데이터를 삭제할 수 있도록 수정해주세요!

```suggestion
    WHERE posts.id = ?
```

2023-01-26 08:21 UTC, sangwoong03 commented on jangjuseong/app.js
> +  );
주성님 해당 부분 결과 사진 좀 볼 수 있을까요!?

2023-01-27 05:07 UTC, jangjuseong commented on jangjuseong/app.js
> +  );
<img width="847" alt="스크린샷 2023-01-27 오후 2 04 57(2)" src="https://user-images.githubusercontent.com/115794886/215013696-f1f4d51b-9da7-46fb-bf19-82fba68de4d1.png">
<img width="1338" alt="스크린샷 2023-01-27 오후 2 04 57" src="https://user-images.githubusercontent.com/115794886/215013701-5caa881e-3bb7-419e-b074-ec933e78ef60.png">

2023-01-29 14:43 UTC, sangwoong03 approved these changes
고생하셨습니다!
LGTM 👍

2023-01-29 14:43 UTC, merged