[42기 강신혜] 과제2: 회원가입 기능 구현
wecode-bootcamp-korea/42-backend-westagram-1 pull request #7
Opened 2023-01-23 15:23 UTC by ksh0123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 회원가입 기능 구현
- 알맞은 API 호출 URL 설정
- 알맞은 http 메소드 선정
- 알맞는 http 상태코드 반환

<br />

## :: 구현 사항 설명 
- 유저 정보를 백엔드 서버에 전달
- 데이터 생성 후 db에 저장

<br />

## :: 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/122417190/214077515-f93bb63b-da3c-47c8-8f73-242005bac9d0.png)

![image](https://user-images.githubusercontent.com/122417190/214077604-c01e89fd-2978-455e-93a4-9f2340299811.png)

<br />

## :: 기타 질문 및 특이 사항
.gitignore 파일에 schema.sql을 추가했는데도 불구하고 업로드 된 것 같습니다.

2023-01-24 14:46 UTC, sangwoong03 requested changes

2023-01-24 14:46 UTC, sangwoong03 commented on shinhye/.gitignore
> +/schema.sql
해당 부분에서 명확한 경로를 지정해주는 것이 좋을 것 같습니다.

추가로 이미 github에 push가 된 파일을 삭제하는 방법은 다음과 같습니다.
`git rm --cached "filepath"`
이 때 해당 명령어를 입력했을 때 터미널에서 아래와 같은 메시지를 본 이후 다시 push 해주세요!:
`rm: ... `

```suggestion
db/schema.sql
```

2023-01-24 14:46 UTC, sangwoong03 commented on shinhye/app.js
> +
깔끔하네요!!

주석 처리를 통해 해당 API가 어떤 기능인지 적어주는 것도 분명히 좋은 효과를 낼 수 있습니다.
하지만 코드를 수정하게 되어 일반 회원가입이 아닌, 소셜로그인 혹은 다른 기능으로 바뀐다면 주석도 그에 맞게 수정을 해야하는 소요가 있습니다.
이 때 주석을 제대로 수정하지 않는다면 다른 팀원에게 오히려 혼란을 줄 수도 있습니다.

지금은 학습 목적이고 구분하기 위해 주석 처리를 하지만, 나중에는 추가 구현 사항을 위해 혹은 다른 팀원에게 전달할 내용이 있는 경우 주석을 남기기도 하는데요. 특정 상황을 제외하고, 코드에 대한 설명을 추가하기 전에 내가 `좀 더 가독성이 좋은 코드를 쓸 수 있지 않을까?` 에 대한 고민도 좋을 것 같습니다.

우선은 주석은 삭제해도 좋을 것 같네요! 👍

2023-01-24 14:46 UTC, sangwoong03 commented on shinhye/db/migrations/20230123101317_create_users_table.sql
> +);
특정 서비스를 이용하면서 회원가입을 할 때 아이디나 이메일에 대해 중복 여부를 확인한 적이 있을 것입니다.

클라이언트 혹은 코드로서 중복 처리를 막아낼 수 있지만, 다른 경로를 통해 데이터가 주입될 수 있는 경우도 있습니다.

미니과제) 이런 문제를 방지하기 위해 데이터베이스 상에서도 중복을 방지할 수 있도록 이메일 컬럼에 UNIQUE 제약 조건을 추가하는 sql 파일을 추가해주세요!!

2023-01-25 01:58 UTC, ksh0123 commented on shinhye/db/migrations/20230123101317_create_users_table.sql
> +);
상웅님 피드백을 제대로 이해한 것 같은데요! 
올바르게 반영하기 위해 아래 질문드립니다.

제약 조건을 설정하는 문법에는 2가지가 있다고 이해하고 있습니다.
1) email VARCHAR(512) NOT NULL UNIQUE
2) CONSTRAINT UQ_Users_Email UNIQUE email

미니과제 대로 2번 문법으로 다시 설정하자면 위와 같이 수정할 것 같습니다.

관련해서 제 질문은, 
Q1. 이 과제에서는 1번 문법으로 설정하면 뮤효한지?
그렇다면 데이터베이스에 설정되어 있는 UNIQUE를 초기화하고 다시 설정해야 되는 건지?
(mysql 데이터베이스 상에서는 이 문법으로 적용되어 있는 것으로 확인됩니다!)
<img width="503" alt="image" src="https://user-images.githubusercontent.com/122417190/214462666-8976fb3e-56e6-4f5a-aa35-cd788ba264e7.png">

Q2. 향후 과제에서는 2번 문법과 같이 제약조건에 이름을 설정하는 방식을 지향해야 하는 것인지?가 궁금합니다!

2023-01-25 06:07 UTC, ksh0123 commented on shinhye/.gitignore
> +/schema.sql
피드백 반영했습니다!

2023-01-25 06:07 UTC, ksh0123 commented on shinhye/app.js
> +
피드백 반영했습니다!

2023-01-25 06:22 UTC, ksh0123 commented on shinhye/.gitignore
> +/schema.sql
아래 피드백을 처음에는 '애커프에서 애드 커밋을 제외하고 푸시를 바로 진행하라'는 피드백으로 이해했고,
그대로 진행했더니 해당 파일이 삭제가 안되는 현상을 확인했습니다.
> 해당 명령어를 입력했을 때 터미널에서 아래와 같은 메시지를 본 이후 다시 push 해주세요!

<img width="775" alt="image" src="https://user-images.githubusercontent.com/122417190/214494588-ad23bfd4-b40e-4647-a134-feb40db55bc3.png">

그래서 git rm -- cached "filepath"로 schema.sql 삭제 -> 삭제된 파일 제외한 전체파일 애드 -> 전체파일 커밋 플로우로 해결해 봤는데요. 이보다 더 나은 방법이나 놓친 부분이 있다면 말씀해 주세요.

2023-01-25 06:42 UTC, sangwoong03 approved these changes
LGTM 👍  고생하셨습니다.

2023-01-25 06:42 UTC, merged