[42기 강신혜] 과제3~8: 포스팅 및 라이크 기능 구현
wecode-bootcamp-korea/42-backend-westagram-1 pull request #9
Opened 2023-01-29 08:22 UTC by ksh0123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 게시글 등록 기능 구현
- 전체 게시글 조회 기능 구현
- 유저 게시글 조회 기능 구현
- 게시글 수정 기능 구현
- 게시글 삭제 기능 구현
- 좋아요 기능 구현 

<br />

## :: 구현 사항 설명
- 포스팅, 라이크 데이터베이스 세팅
- 유저, 게시물, 라이크 데이터 생성 후 db에 저장

<br />

## :: 테스트 결과 이미지
1. 과제3 게시물 등록 이미지
![image](https://user-images.githubusercontent.com/122417190/215312028-83ff915f-3461-4057-91d5-ace55a9790d2.png)

2. 과제4 전체 게시물 조회 이미지
![image](https://user-images.githubusercontent.com/122417190/215312066-d99f3bfa-f312-4f93-8458-d56f046ed2f7.png)

3. 과제5 유저 게시글 조회 이미지
<img width="1508" alt="assignment5" src="https://user-images.githubusercontent.com/122417190/215313609-a288a916-333d-4296-ac69-e5c13c05fbb0.png">

4. 과제6 게시글 수정 이미지
![image](https://user-images.githubusercontent.com/122417190/215313617-c66ddef8-031d-4941-8812-a2d243a51601.png)

5. 과제7 게시글 삭제 이미지
![image](https://user-images.githubusercontent.com/122417190/215312211-979c0803-7fa6-45d3-99a0-831e8ac96bf2.png)

6. 과제8 좋아요 이미지
![image](https://user-images.githubusercontent.com/122417190/215312226-5daafd86-f3b4-43f3-95d2-b82481f3ec35.png)

<br />

## :: 기타 질문 및 특이 사항
- 과제5 유저 게시글 조회: 유저 1의 포스트 1을 반환할 때, 배열의 형태를 띄고 있지만 의도된 것은 객체로 반환하는 것입니다. 하지만 typeof 로 결과물을 확인해보면 object라고 뜹니다. 정보 타입과 구문이 일치하지 않는 문제는 어떻게 처리하는 것이 좋을까요?
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/122417190/215314340-4f242529-be47-47ef-bfa4-2f2969b2bb22.png">

2023-01-29 15:11 UTC, sangwoong03 reviewed
고생하셨습니다!

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked_post_id INT NOT NULL,
컬럼명 수정해주세요!
`like_`로 작성한다면 `like` 테이블을 조회할 때 `likes_like_user_id`로 조회를 할 것입니다.

그럴 필요 없이 `like_user_id`로 바로 접근할 수 있도록 수정하면 좋을 것 같습니다.

해당 부분과 관련된 부분 모두 수정해주세요!
```suggestion
    user_id INT NOT NULL,
    post_id INT NOT NULL,
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/db/migrations/20230126075942_create_posts_table.sql
> +    user_profile_image VARCHAR(512) NULL,
user의 프로필 이미지는 유저와 관련된 데이터이므로 `posts` 테이블보다 `users` 테이블에서 관리하는 것이 좋을 것 같습니다.

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/db/migrations/20230126075942_create_posts_table.sql
> +    post_content VARCHAR(512) NULL,
컬렴명 수정해주세요!

작성하신 부분처럼 컬럼명을 관리한다면 `posts_post_image_url`로 조회하게 됩니다.

`posts_image_url`로 조회했을 때도 그 의미와 결과값을 예측할 수 있기 때문입니다.

해당 부분과 관련된 코드를 모두 수정해주세요!
```suggestion
    image_url VARCHAR(512) NOT NULL,
    content VARCHAR(512) NULL,
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +  );
쿼리문 포매팅을 수정해주세요!
적절한 들여쓰기와 구조적 통일성을 통해 가독성을 향상시키고 코드를 유지보수하기도 용이해집니다.
```suggestion
  const postData = await AppDataSource.query(`
    SELECT
      user_id as userID,
      user_profile_image as userProfileImage,
      id as postId,
      post_image_url as postImageUrl,
      post_content as postContent
    FROM posts;
    `);
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +  );
해당 부분도 코드 포매팅을 수정해주세요!
```suggestion
  await AppDataSource.query(
    `
    UPDATE posts
    SET
      post_content = ?
    WHERE user_id = ? AND id = ?;
    `,
    [postContent, userID, postID]
  );

  const updatedPost = await AppDataSource.query(
    `
    SELECT
      users.id as userID,
      users.username,
      posts.id as postID,
      posts.post_content as postContent
    FROM users
    INNER JOIN posts ON posts.user_id = users.id
    WHERE posts.user_id = ? AND posts.id= ?;
    `,
    [userID, postID]
  );
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +app.get("/posts/:userID", async (req, res) => {
마이너하지만 path-parameter 네이밍 수정해주세요!
```suggestion
app.get("/posts/:userId", async (req, res) => {
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +  const { userID } = req.params;
마이너하지만 path-parameter 네이밍 수정해주세요!
관련된 query 문도 수정해주세요.
```suggestion
  const { userId } = req.params;
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +app.delete("/posts/:postID", async (req, res) => {
마이너하지만 path-parameter 네이밍 수정해주세요!

```suggestion
app.delete("/posts/:postId", async (req, res) => {
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +  const { postID } = req.params;
마이너하지만 path-parameter 네이밍 수정해주세요!

```suggestion
  const { postId } = req.params;
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/app.js
> +  const { userID, postID } = req.body;
body 데이터로 받는 key 값도 수정해주면 좋을 것 같습니다.
```suggestion
  const { userId, postId } = req.body;
```

2023-01-29 15:11 UTC, sangwoong03 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked BOOLEAN NOT NULL DEFAULT TRUE,
해당 컬럼은 어떤 데이터를 관리하는지 설명 부탁드립니다!

2023-01-30 01:50 UTC, sangwoong03 commented
>과제5 유저 게시글 조회: 유저 1의 포스트 1을 반환할 때, 배열의 형태를 띄고 있지만 의도된 것은 객체로 반환하는 것입니다. 하지만 typeof 로 결과물을 확인해보면 object라고 뜹니다. 정보 타입과 구문이 일치하지 않는 문제는 어떻게 처리하는 것이 좋을까요?
첫번째 질문에 대한 답변은 다음과 같습니다.
TypeOrm의 `query( raw-query )` 메서드는 실제 MySQL이 반환하는 raw-data를 반환합니다.
`select ... from ` 구문이 반환하는 값의 형식은 다음과 같습니다: `[ { feild: data } ]`
따라서 우리가 데이터베이스에서 데이터를 조회하고 그 값을 반환하기 위해서는 다음과 같이 작성해주면 됩니다
```javascript
const userPosts = await appDataSource.query( raw-query )
...
return res.json({ data: userPosts[0] })
// 혹은
const [userPosts] = await appDataSource.query( raw-query)
...
return res.json({ data: userPosts })
```
추가로 JavaScript의 Array는 다른 언어의 배열이라는 데이터 타입을 갖고 있지 않습니다.
array는 array의 기능을 하는 object입니다. 그렇기 때문에 타입 자체는 object로 반환이 됩니다.
해당 부분은 자료구조와 데이터타입에 대한 자료를 통해 어떤 차이가 있는지 찾아보면 도움이 되실 것 같습니다.
>과제 7 게시글 삭제: 게시글을 삭제하면 해당 글의 라이크 정보도 함께 삭제하기 위해 아래와 같은 코드를 작성했습니다. 하지만 오류가 발생해서, 라이크 정보 삭제와 포스팅 정보 삭제 순서를 변경해 보았는데, 오류가 해결되었습니다. await을 사용하는 비동기 함수는 순서대로 수행되지 않는 것으로 알고 있는데, 이 경우에는 라이크 데이터 삭제가 선해되어야 하는 이유가 있을까요?

작성해주신 `likes` 테이블은 `posts` 테이블을 참조하고 있습니다. 그렇기 때문에 post_id 값을 갖고 있는 데이터가 `likes` 내에 존재한다면, `posts` 테이블의 해당 데이터를 삭제할 수 없는 것입니다.
비동기 코드가 실행될 때는 특정 코드가 처리되는 시간을 기다리지 않고 곧바로 다음 코드를 실행하기 때문에 순서가 상관 없는 것처럼 보이는 것입니다. 만약 게시글을 지우는 함수 자체가 실행되는 도중 좋아요 정보를 삭제하는 코드가 실행이 될 텐데 앞서 설명드린 것처럼 게시글을 지우는 것 자체가 오류가 발생하기 때문에 코드가 의도대로 동작하지 않는 것입니다.

2023-01-30 02:55 UTC, ksh0123 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked_post_id INT NOT NULL,
넵 반영했습니다!

2023-01-30 03:15 UTC, ksh0123 commented on shinhye/db/migrations/20230126075942_create_posts_table.sql
> +    post_content VARCHAR(512) NULL,
넵 반영했습니다!

2023-01-30 03:51 UTC, ksh0123 commented on shinhye/app.js
> +  );
넵 반영했습니다!

2023-01-30 03:53 UTC, ksh0123 commented on shinhye/app.js
> +  );
넵 반영했습니다!

2023-01-30 03:53 UTC, ksh0123 commented on shinhye/app.js
> +app.get("/posts/:userID", async (req, res) => {
넵 반영했습니다!

2023-01-30 03:53 UTC, ksh0123 commented on shinhye/app.js
> +  const { userID } = req.params;
넵 반영했습니다!

2023-01-30 03:54 UTC, ksh0123 commented on shinhye/app.js
> +app.delete("/posts/:postID", async (req, res) => {
넵 반영했습니다!

2023-01-30 03:55 UTC, ksh0123 commented on shinhye/app.js
> +  const { postID } = req.params;
넵 반영했습니다!

2023-01-30 03:55 UTC, ksh0123 commented on shinhye/app.js
> +  const { userID, postID } = req.body;
넵 반영했습니다!

2023-01-30 04:01 UTC, ksh0123 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked BOOLEAN NOT NULL DEFAULT TRUE,
Liked 열은 유저가 라이크를 눌렀을 때의 상태를 부울 형태로 기록하도록 추가했습니다.
유저가 게시글을 like하면 디폴트값으로 TRUE(1)가 적용되도록 했고,
해당 게시물을 다시 like하면, 아래 조건에 따라서 TRUE는 FALSE로 변경되어 라이크를 취소하도록 했습니다. 
`ON DUPLICATE KEY UPDATE liked= NOT liked;`

2023-01-30 05:14 UTC, ksh0123 commented on shinhye/db/migrations/20230126075942_create_posts_table.sql
> +    user_profile_image VARCHAR(512) NULL,
넵 반영했습니다!

2023-01-30 18:31 UTC, sangwoong03 requested changes
데이터베이스 테이블 컬럼 한번만 수정해주세요!
코드 깔끔하게 잘 작성해주셨네요 ㅎㅎ

2023-01-30 18:31 UTC, sangwoong03 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked BOOLEAN NOT NULL DEFAULT TRUE,
유저 한명이 게시글 하나에 좋아요를 하나밖에 못하기 때문에 해당 컬럼으로 관리를 하는 것도 좋은 방법일 수 있습니다! 

하지만 아래 unique 설정을 통해서도 충분히 관리가 될 것 같습니다!

삭제해도 괜찮을 것 같습니다!

2023-01-30 23:10 UTC, ksh0123 commented on shinhye/db/migrations/20230127012509_create_likes_table.sql
> +    liked BOOLEAN NOT NULL DEFAULT TRUE,
넵 감사합니다. 궁금한 점이 있습니다!

아래 코드만 삭제하면 된다는 말씀이신가요?
> liked BOOLEAN NOT NULL DEFAULT TRUE

1) 그렇다면 Created_at, Updated_at 열도 삭제가 필요할 것 같은데, 다른 용도가 있을 수 있을까요? 원래 작성했던 이유는 좋아요 시점과 좋아요 해지 시점을 기록하기 위해 created_at, updated_at 열을 추가했었습니다. Liked 열을 삭제하면 용도가 없을 것 같습니다.

2) Unique 설정으로 관리가 된다는 것이 어떤 의미인지 좀 더 설명 부탁드리겠습니다! 제가 UQ_Like 제약조건을 추가한 이유는 말씀하신 대로 라이크를 한 번만 누르기 위해서 인데요. 위에 삭제가 필요한 코드는 횟수제약을 위한 코드가 아닌 설정/해지 기능을 위해 작성했었습니다.

2023-01-31 01:09 UTC, sangwoong03 approved these changes
고생하셨습니다🔥

2023-01-31 01:09 UTC, merged